# Generated by Django 2.2.5 on 2020-02-09 14:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0005_auto_20200209_2200'),
    ]

    operations = [
        migrations.DeleteModel(
            name='ReadNum',
        ),
    ]
